# Generated by Django 3.2.16 on 2023-10-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
