# Generated by Django 3.2.16 on 2023-10-04 05:36

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20231004_0531'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='self_following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('following')), _negated=True), name='self_following'),
        ),
    ]
